### ISSUE TITLE
`app/views/app/_default.html` uses texts from the diaspora* upstream project without attribution

### ISSUE THREAD

**Issue by denschub** [ganggo/ganggo#22]
The texts in `app/views/app/_default.html` are taken from diaspora\*s default index template in diaspora\*s localization files. Since this is not a modification of the diaspora sources, but rather a completely different project which is even licensed under a difference license (GPL vs. AGPL), the current usage is somewhat violating the diaspora\* code license terms.

Even if this is just a minor case, I personally pretty much dislike projects just copying stuff from other projects, even if they are using similar technology. Please either include a note to the AGPL as [referenced in the header of the original sources](https://github.com/diaspora/diaspora/blob/42a81290163f559a54db9d8193afdcbeba834269/config/locales/diaspora/en.yml) in your code, or alternatively, use the texts under CC-BY 3.0 as the official project site is licensed as such and texts are cross-referenced. Using AGPL is probably more convenient since it does not require a visual license note in the frontend.

**Comment by denschub** [comment]
You are kidding me, right?

**Comment by christophehenry** [comment]
> You are kidding me, right?

I don't think so. Of course, you could try to demonstrate in court there's a copyright issue. But I think the judge would laugh at you. After all, there's no copyright on words and ideas :wink:

**Comment by denschub** [comment]
Ah, thanks Augier for your opinion. Sadly, you are wrong, and there have been multiple cases showing exact that.

But you know what? Fine. Go ahead. I noted that you and, apparently, Lukas do not care about how open source works and that you are not able to show any respect towards other peoples work.

Sorry that I assumed basic human decency and common sense.

**Comment by Zauberstuhl** [comment]
>  I noted that you and, apparently, Lukas do not care about how open source works and that you are not able to show any respect towards other peoples work.

I do and I know I did something wrong by using the text. That is why I rephrased it.

**Comment by denschub** [comment]
"Rephrasing" it is the wrongest, and, to be fair, the most ridiculous thing you could have done. Not only do you still violate copyrights since "rephrasing" texts does not change anything, it also shows that you'd rather "rephrase" stuff than to add a license note that isn't even visible to the users.

I stopped caring. Do whatever you want.

**Comment by christophehenry** [comment]
> But you know what? Fine. Go ahead. I noted that you and, apparently, Lukas do not care about how open source works and that you are not able to show any respect towards other peoples work.

Ah well... Here you go again with that raging insulting monomaniac behavior. It's fine. I don't have anything to prove you in addition to that I'm not an active developer of the project and not responsible for these changes...

I just think you are making a fuss for nothing and I'm surprised you have time to lose on checking for copyright issues in the texts of an application that has been used by literally no one yet. But, eh, I'm not judging your hobbies :)

**Comment by Zauberstuhl** [comment]
Since rephrasing is not OK I simply deleted it https://github.com/ganggo/ganggo/pull/24
It is that simple no reason for shitstorming anyone!
