### ISSUE TITLE
Are you, certainly, open source or maybe are you free software, or software libre?

### ISSUE THREAD

**Issue by aldobelus0** [ganggo/ganggo#66]
Hi. I only want to remember you about the words of Stallman and GNU Project, saying that is not the same open source than free software. And it is better to call it as it is, because is more accurate and the free software need to be known. 

Thanks for your attention, congratulations for your platform, and greetings!

**Comment by Zauberstuhl** [comment]
Hi,

reading about FOSS, FLOSS, Free Software and Open Source my understanding is that;
Its the same and we only try to avoid mistakes like this `To emphasize that “free software” refers to freedom and not to price, [...]` (quote from http://www.gnu.org/philosophy/floss-and-foss.en.html)

I call it open source, cause

* the software is free available (free like in no charges/prices)
* it comes with a licenses approved/accepted by the [Free Software Foundation Europe](https://fsfe.org/campaigns/gplv3/gplv3.en.html)
* cause in my opinion free software can be proprietary too
* cause libre translates to free and is for me only a indicator for non-proprietary software and that can be avoided by simply not using the word free/libre

Does that answer your question?
